### ISSUE TITLE
precision_recall_fscore_support

### ISSUE THREAD

**Issue by algorithmdog** [sushobhannayak/cssag#2]
Hi, sushobhannayak. I have encounter a problem when I use the code:
[xxx@saussure cssag]$ python2  hierarchicalMultiLabelLearning.py -i hierarchy.dat -e test.svmlight.mini -a train.svmlight.mini -x test.labels.mini -y train.labels.mini 
reached to idx:  1000
reached to idx:  100
training model.......pca:  kpca regressor:  ridge dim:  50 tree:  or
Input data and label shape:  (1000, 60095) (1000, 2938)
at regressor number:  0
at regressor number:  1
at regressor number:  2
at regressor number:  3
at regressor number:  4
at regressor number:  5
at regressor number:  6
at regressor number:  7
at regressor number:  8
at regressor number:  9
at regressor number:  10
at regressor number:  11
at regressor number:  12
at regressor number:  13
at regressor number:  14
at regressor number:  15
at regressor number:  16
at regressor number:  17
at regressor number:  18
at regressor number:  19
at regressor number:  20
at regressor number:  21
at regressor number:  22
at regressor number:  23
at regressor number:  24
at regressor number:  25
at regressor number:  26
at regressor number:  27
at regressor number:  28
at regressor number:  29
at regressor number:  30
at regressor number:  31
at regressor number:  32
at regressor number:  33
at regressor number:  34
at regressor number:  35
at regressor number:  36
at regressor number:  37
at regressor number:  38
at regressor number:  39
at regressor number:  40
at regressor number:  41
at regressor number:  42
at regressor number:  43
at regressor number:  44
at regressor number:  45
at regressor number:  46
at regressor number:  47
at regressor number:  48
at regressor number:  49
prediction shapes: 50 100
testing the regressor model...
Traceback (most recent call last):
  File "hierarchicalMultiLabelLearning.py", line 359, in <module>
    data_reg = pres_rec_f1(Y_true, Y_preds_list)
  File "hierarchicalMultiLabelLearning.py", line 289, in pres_rec_f1
    p, r, f, s = precision_recall_fscore_support(Y_true, Y_preds_list[n], average='samples')
TypeError: precision_recall_fscore_support() got an unexpected keyword argument 'average'

It seems the sklearn.metric.precision_recall_fscore_support doesn't accept the keyword argument "average", even after updating my sklearn to the latest.

**Comment by sushobhannayak** [comment]
It was working as far as I remember. Also see here:
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_fscore_support.html.
it does have the average argument. Try and see if sklearn is >=14? I am not
sure what else the pb might be. Please let me know if you figure out.

Sushobhan

**Comment by algorithmdog** [comment]
I figure this problem by reinstalling my sklearn. Thanks you all the time.
